input = input("Input:")
print(input)
input = input.replace('a', '').replace('e', '').replace('i', '').replace('o', '').replace('u', '')
input = input.replace('A', '').replace('E', '').replace('I', '').replace('O', '').replace('U', '')
print(input)